# Generated by Django 5.0.1 on 2024-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='I1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='I2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='I3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='I4',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='i_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='story',
            field=models.TextField(default=None, null=True),
        ),
    ]
