# Generated by Django 5.0.1 on 2024-01-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anime',
            new_name='m_anime',
        ),
    ]
