# Generated by Django 5.0.1 on 2024-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_rename_anime_m_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dis', models.TextField(default=None, null=True)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='anime/')),
            ],
        ),
        migrations.CreateModel(
            name='b_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dis', models.TextField(default=None, null=True)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='anime/')),
            ],
        ),
        migrations.CreateModel(
            name='c_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dis', models.TextField(default=None, null=True)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='anime/')),
            ],
        ),
        migrations.DeleteModel(
            name='m_anime',
        ),
    ]
