# Generated by Django 5.0.1 on 2024-01-28 11:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_airing',
            name='top_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
