# Generated by Django 5.0.1 on 2024-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_top_airing_top_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_airing',
            name='i1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='top_airing',
            name='i2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='top_airing',
            name='i3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='top_airing',
            name='i4',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='top_airing',
            name='i_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='top_airing',
            name='story',
            field=models.TextField(default=None, null=True),
        ),
    ]
