# Generated by Django 5.0.1 on 2024-02-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_top_airing_i1_top_airing_i2_top_airing_i3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_airing',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='top_airing',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='top_airing',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='top_airing',
            name='i4',
        ),
        migrations.RemoveField(
            model_name='top_airing',
            name='i_img',
        ),
        migrations.RemoveField(
            model_name='top_airing',
            name='story',
        ),
    ]
