# Generated by Django 5.0.1 on 2024-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending_anime',
            name='img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='trending/'),
        ),
    ]
