# Generated by Django 5.0.1 on 2024-02-01 11:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0005_remove_trending_anime_i1_remove_trending_anime_i2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending_anime',
            name='trend_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
