# Generated by Django 5.0.1 on 2024-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_movies',
            name='img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='anime_movies/'),
        ),
    ]
