# Generated by Django 5.0.1 on 2024-01-28 11:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_anime_movies_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_movies',
            name='movie_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
