# Generated by Django 5.0.1 on 2024-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_anime_movies_movie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime_movies',
            old_name='dic',
            new_name='dis',
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='i1',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='i2',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='i3',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='i4',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='i_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='anime_movies',
            name='story',
            field=models.TextField(default=None, null=True),
        ),
    ]
