# Generated by Django 5.0.1 on 2024-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recent',
            new_name='recently_updated',
        ),
    ]
