# Generated by Django 5.0.1 on 2024-01-28 10:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent', '0002_rename_recent_recently_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recently_updated',
            name='recent_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
