# Generated by Django 5.0.1 on 2024-02-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent', '0004_recently_updated_i1_recently_updated_i2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recently_updated',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='i4',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='i_img',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='recent_slug',
        ),
        migrations.RemoveField(
            model_name='recently_updated',
            name='story',
        ),
    ]
